name: Build ADB Tools
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
      - run: flutter build windows
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: WallpaperTools
          path: build\windows\x64\runner\Release\
